### PR TITLE
Add checkbox icon for selected variant

### PR DESCRIPTION
**Pull request by WebDevRaj**
There is only Blank checkbox icon implemented as of now. I have added Checked icon to show the selected variant

### CODE REVIEW

**Comment by ManojSatishkumar** [comment]
Screenshot please

**Comment by WebDevRaj** [comment]
Screenshot (34)

**Comment by WebDevRaj** [comment]
> Screenshot please

Screenshot (34)

**Comment by ManojSatishkumar** [comment]
@WebDevRaj , Can you add a background color as slightly darker gray instead?
Checkboxes give a different impression that you can select multiple variants.

**Comment by WebDevRaj** [comment]
> @WebDevRaj , Can you add a background color as slightly darker gray instead?
> Checkboxes give a different impression that you can select multiple variants.

Sure. I'll do that. Should I leave the icon as it is or change it to something else?

**Comment by WebDevRaj** [comment]
Screenshot (35)


> @WebDevRaj , Can you add a background color as slightly darker gray instead?
> Checkboxes give a different impression that you can select multiple variants.
Screenshot (35)

@ManojSatishkumar Also changed the font color, Please have a look.

**Comment by ManojSatishkumar** [comment]
Looks good

**Comment by WebDevRaj** [comment]
> @WebDevRaj , Can you add a background color as slightly darker gray instead?
> Checkboxes give a different impression that you can select multiple variants.

Screenshot (15)
@ManojSatishkumar Also changed the font color, Please have a look.

**Pull request merged**
